ADDRESS_FURNACE=1
ADDRESS_FURNACE_DETAILS=2
#GREEN
ADDRESS_LIGHTS_BLIND_ON=10
ADDRESS_LIGHTS_BLIND_OFF=11
#BLUE
ADDRESS_LIGHTS_WINDOW_ON=20
ADDRESS_LIGHTS_WINDOW_OFF=21

#BLUE
ADDRESS_LIGHTS_1=30
ADDRESS_LIGHTS_2=31
ADDRESS_LIGHTS_3=32

#INPUTS
ADDRESS_TEMPERATURE=0
ADDRESS_RAIN=1

ADDRESS_ALL_LIGHTS = [
    ADDRESS_LIGHTS_BLIND_ON, ADDRESS_LIGHTS_BLIND_OFF, ADDRESS_LIGHTS_WINDOW_ON, ADDRESS_LIGHTS_WINDOW_OFF, ADDRESS_LIGHTS_1, ADDRESS_LIGHTS_2, ADDRESS_LIGHTS_3
]